config/routes.rb
Oneking::Application.routes.draw do

root :to => "sessions#new"

resources :users
resources :sessions
resources :queries
resources :orders

get "sessions/new"
get "users/new"
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "query_page" => "queries#new", :as => "query_page"
get "orders/index"

end

app/models/address.rb
class Address < ActiveRecord::Base
 attr_accessible :address_id, :first_name, :last_name, :address_1, 
 :address_2, :postal_code, :city, :phone, :created_by, :created_date, 
 :modified_by, :modified_date
  
end

app/models/customer.rb
# TO DO: Encrypt password. Need hash and salt fields on DB


class Customer < ActiveRecord::Base
 attr_accessible :customer_id, :first_name, :last_name, 
 :email_address, :postal_code, :password, :status, :date_added, 
 :created_by, :created_date, :modified_by, :modified_date, :is_deleted

  validates_presence_of :password, :on => :create
  validates_presence_of :email_address
  validates_uniqueness_of :email_address
  validates_format_of :email_address, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  
end

app/models/email_preference.rb
class Email_preference < ActiveRecord::Base
 attr_accessible :customer_id, :subscribes_to_daily_emails, 
 :subscribes_to_special_promos, :subscribes_to_weekly_calendar, 
 :created_by, :created_date, :modified_by, :modified_date, :is_deleted
  
end

app/models/order.rb
class Order < ActiveRecord::Base
 attr_accessible :order_id, :customer_id, :first_name, :last_name, 
 :email_address, :shipping_address_id, :payment_method_id, :total_amount,
  :tax_amount, :gift_card_amount, :shipping_amount, :handling_amount, 
  :order_date, :submitted_date, :status, :created_by, :created_date, 
  :modified_by, :modified_date, :is_deleted
  

  def self.query(order_id)
    orders = order(:order_id)
    orders = orders.where("order_id = ?", order_id) if order_id.present?
    orders
  end

end

app/models/query.rb
class Query < ActiveRecord::Base
  attr_accessible :customer_email, :customer_first_name, :customer_last_name, :max_total_amount,
   :min_total_amount, :order_id, :order_is_deleted, :order_max_date, :order_min_date, :results_limit, :postal_code, :subscribes_to_daily_emails

def orders
    @orders ||= find_orders
end
  
#TO DO:
#1. Pagination:
#2. Add limit if not present when there could be too many results. DONE! Set limit to 50.
#3. Add export feature and remove limit for export.

private
  def find_orders

@results_limitVar = nil

if results_limit.nil? == true
    @results_limitVar = 50
else
    @results_limitVar = results_limit    
end
   
@subscribes_to_daily_emailsVar = nil

if subscribes_to_daily_emails.nil? == false
  if subscribes_to_daily_emails 
    @subscribes_to_daily_emailsVar = 1
  else 
    @subscribes_to_daily_emailsVar = 0
  end
end


@order_is_deletedVar = nil

if order_is_deleted.nil? == false
  if order_is_deleted 
    @order_is_deletedVar = 1
  else 
    @order_is_deletedVar = 0
  end
end

#Added orders explicitly because otherwise first_name, etc is ambiguous 
#since it is in multiple models.

    orders = Order.order(:order_id)
    orders = orders.where("orders.first_name LIKE ?", "%#{customer_first_name}%") if customer_first_name.present?
    orders = orders.where("orders.last_name LIKE ?", "%#{customer_last_name}%") if customer_last_name.present?    
    orders = orders.where("orders.email_address LIKE ?", "%#{customer_email}%") if customer_email.present?        
    orders = orders.where("orders.order_id like ?", "%#{order_id}%") if order_id.present?
    orders = orders.where("orders.is_deleted = ?", "#{@order_is_deletedVar}") if !@order_is_deletedVar.nil?
    orders = orders.where("total_amount >= ?", min_total_amount) if min_total_amount.present?
    orders = orders.where("total_amount <= ?", max_total_amount) if max_total_amount.present?
    orders = orders.where("order_date >= ?", order_min_date) if order_min_date.present?
    orders = orders.where("order_date <= ?", order_max_date) if order_max_date.present?
    orders = orders.joins("INNER JOIN customers ON customers.customer_id = orders.customer_id AND customers.postal_code LIKE ", "'%#{postal_code}%'") if postal_code.present?
    orders = orders.joins("INNER JOIN email_preferences ON email_preferences.customer_id = orders.customer_id AND email_preferences.subscribes_to_daily_emails = ", "#{@subscribes_to_daily_emailsVar}") if !@subscribes_to_daily_emailsVar.nil?  
    orders = orders.limit(@results_limitVar) if !@results_limitVar.nil? 
    orders
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]

  # If th DB is cleared but a user exists in the client there will be an error.
  rescue ActiveRecord::RecordNotFound

end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

#NOTE that we have chosen a different pk than the rails default ('id')

  def show
    @orders = Order.find(params[:id])
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

before_filter :require_login

  def new
	  @query = Query.new
  end

  def create
    @query = Query.create!(params[:query])
    redirect_to @query
  end
  
  def show
    @query = Query.find(params[:id])
  end

private

  def require_login
    unless current_user
      redirect_to root_url , :notice => "You need to log in to use the query page!"
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

skip_before_filter :require_user 

	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to :controller => 'queries', :action => 'new' , :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end

	def require_user
  		redirect_to login_path unless current_user
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter :require_login

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to root_url, :notice => "Account Created!"
	  else
	    render "new"
	  end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oneking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="user_nav">

  <% if current_user %>

    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>

  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<%= yield %>

</body>
</html>

app/views/orders/_order.html.erb
<tr>
	<td width="10"><%= link_to order.order_id, order %></td>
	<td width="10"><%= order.customer_id %></td>
	<td width="10"><%= order.first_name %></td>
	<td width="10"><%= order.last_name %></td>
	<td width="10"><%= order.email_address %></td>
	<td width="10"><%= order.shipping_address_id %></td>
	<td width="10"><%= order.payment_method_id %></td>
	<td width="10"><%= number_to_currency(order.total_amount) %></td>
	<td width="10"><%= number_to_currency(order.tax_amount) %></td>
	<td width="10"><%= number_to_currency(order.gift_card_amount) %></td>
	<td width="10"><%= number_to_currency(order.shipping_amount) %></td>
	<td width="10"><%= number_to_currency(order.handling_amount) %></td>
	<td width="10"><%= order.order_date %></td>
	<td width="10"><%= order.submitted_date %></td>
	<td width="10"><%= order.status %></td>
	<td width="10"><%= order.created_by %></td>
	<td width="10"><%= order.created_date %></td>
	<td width="10"><%= order.modified_by %></td>
	<td width="10"><%= order.modified_date %></td>
	<td width="10"><%= order.is_deleted %></td>
</tr>

app/views/orders/index.html.erb
<h2>Orders</h2>

<%= form_tag orders_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= button_tag "Query by order Id", order_id: nil %>
  </p>
<% end %>

<p><%= link_to "Back to Query", new_query_path %></p>

<div id="orders">
  <%= render @orders %>
</div>

app/views/orders/show.html.erb
<h2>Orders</h2>

<!-- Add this later
<%= form_tag orders_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= button_tag "Query by order Id", order_id: nil %>
  </p>
<% end %>
-->



<!-- 
Make a better form for single order. 
-->



<p><%= link_to "Back to Query Form", new_query_path %></p>

<div id="orders">
<table border="1" bordercolor="#003366" style="background-color:#006699" width="100%" cellpadding="3" cellspacing="3">
	<tr>
		<td width="5">Order ID</td>
		<td width="10">Customer ID</td>
		<td width="10">First Name</td>
		<td width="10">Last Name</td>
		<td width="10">Email Address</td>
		<td width="10">Shipping Address ID</td>		
		<td width="10">Payment Method ID</td>
		<td width="10">Total Amount</td>
		<td width="10">Tax Amount</td>		
		<td width="10">GC Amount</td>		
		<td width="10">Ship Amount</td>		
		<td width="10">Hndl. Amount</td>		
		<td width="10">Order Date</td>		
		<td width="10">Submitted Date</td>		
		<td width="10">Status</td>		
		<td width="10">Created By</td>		
		<td width="10">Created Date</td>
		<td width="10">Modified By</td>
		<td width="10">Modified Date</td>
		<td width="10">Deleted</td>
	</tr>

  <%= render @orders %>

  </table>
</div>

app/views/queries/new.html.erb
<h2>Query orders</h2>

<%= form_for @query do |f| %>
  <div class="fieldQuery">
    <%= f.label :customer_first_name, "First Name" %> 
    <%= f.text_field :customer_first_name %>
  </div>  
  <div class="fieldQuery">
    <%= f.label :customer_last_name, "Last Name" %>
    <%= f.text_field :customer_last_name %>
  </div>  
  <div class="fieldQuery">
    <%= f.label :customer_email, "Email" %>
    <%= f.text_field :customer_email  %>
  </div>  
  <div class="fieldQuery">
    <%= f.label :postal_code, "Postal Code" %>
    <%= f.text_field :postal_code  %>
  </div>  
  <div class="fieldQuery">
    <%= f.label :order_id, "Order ID" %>
    <%= f.text_field :order_id  %>
  </div>   
  <div class="fieldRange">
    <%= f.label :order_min_date, "Date Range" %>
    <%= f.text_field :order_min_date, size: 12  %> -
    <%= f.text_field :order_max_date, size: 12  %>
  </div>
  <div class="fieldRange">
    <%= f.label :min_total_amount, "Amount Range" %>
    <%= f.text_field :min_total_amount, size: 12 %> -
    <%= f.text_field :max_total_amount, size: 12 %>
  </div>
  <div class="fieldQuery">
    <%= f.label :order_is_deleted , "Deleted" %>
    <%= f.select :order_is_deleted, {" " => nil, "Yes" => true, "No" => false}%>
  </div>  
  <div class="fieldQuery">
    <%= f.label :subscribes_to_daily_emails , "Daily Emails Subs" %>
    <%= f.select :subscribes_to_daily_emails, {" " => nil, "Yes" => true, "No" => false}%>
  </div>  
  <div class="fieldQuery">
    <%= f.label :results_limit , "Max Results" %>
    <%= f.text_field :results_limit, size:12 %>
  </div>  

  <div class="actions"><%= f.submit "Query" %></div>
 <% end %>

app/views/queries/show.html.erb
<h2>Query Results</h2>
<p><%= link_to "Back to Query Form", new_query_path %></p>
<table border="1" bordercolor="#003366" style="background-color:#006699" width="100%" cellpadding="3" cellspacing="3">
	<tr>
		<td width="5">Order ID</td>
		<td width="10">Customer ID</td>
		<td width="10">First Name</td>
		<td width="10">Last Name</td>
		<td width="10">Email Address</td>
		<td width="10">Shipping Address ID</td>		
		<td width="10">Payment Method ID</td>
		<td width="10">Total Amount</td>
		<td width="10">Tax Amount</td>		
		<td width="10">GC Amount</td>		
		<td width="10">Ship Amount</td>		
		<td width="10">Hndl. Amount</td>		
		<td width="10">Order Date</td>		
		<td width="10">Submitted Date</td>		
		<td width="10">Status</td>		
		<td width="10">Created By</td>		
		<td width="10">Created Date</td>
		<td width="10">Modified By</td>
		<td width="10">Modified Date</td>
		<td width="10">Deleted</td>
	</tr>

<%= render @query.orders %>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <br/>
  <br/>
  <br/>


<center>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Correct Erors and try again</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</center>
 
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>

<center>

<table border="0" bordercolor=transparent" style="background-color:transparent" width="200">
  <tr>
    <td>
          <%= f.text_field :email, :placeholder => "email address", :class => "field"  %>
          <%= f.password_field :password, :placeholder => "password", :class => "field" %>
          <%= f.password_field :password_confirmation, :placeholder => "confirm password", :class => "field" %>
    </td>
  </tr>
</table>

  <p ><%= f.submit %></p>

<% end %>

or

<%= button_to "Log in", log_in_path, :method => "get" %>


</center>